name: Build Minecraft Mod

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Enables manual trigger

jobs:
  build:
    name: Build Mod
    runs-on: ubuntu-latest

    steps:
      # Checkout the ModernUI-MC repository
      - name: Checkout ModernUI-MC
        uses: actions/checkout@v3

      # Clone the ModernUI repository
      - name: Clone ModernUI
        run: git clone --branch master https://github.com/BloCamLimb/ModernUI ../ModernUI

      # Ensure JDK 23 is available
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      # Grant execution permissions to gradlew
      - name: Set Gradlew Permissions
        run: chmod +x ./gradlew

      # Build the project
      - name: Build with Gradle
        run: ./gradlew build

      # Cache Gradle dependencies to speed up future builds
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Upload the built mod JAR as an artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: minecraft-mod
          path: build/libs/*.jar
